# Generated by Django 3.1.5 on 2021-07-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Received', 'Order Received '), ('Order Completed', 'Order Completed'), ('On The Way', 'On The Way')], max_length=50),
        ),
    ]
