# Generated by Django 3.1.5 on 2021-07-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='quantity',
            new_name='quantaty',
        ),
        migrations.RenameField(
            model_name='cartproduct',
            old_name='sutotal',
            new_name='subtotal',
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('On The Way', 'On The Way'), ('Order Received', 'Order Received '), ('Order Completed', 'Order Completed')], max_length=50),
        ),
    ]
