# Generated by Django 3.1.5 on 2021-08-03 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0002_auto_20210726_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('On The Way', 'On The Way'), ('Order Received', 'Order Received '), ('Order Completed', 'Order Completed')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProdctImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnitureshop.product')),
            ],
        ),
    ]
