# Generated by Django 3.1.5 on 2021-11-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0003_auto_20210803_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Happycustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('description', models.TextField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('On The Way', 'On The Way'), ('Order Received', 'Order Received ')], max_length=50),
        ),
    ]
