# Generated by Django 3.1.5 on 2021-07-14 14:38

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0003_auto_20210714_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default=datetime.datetime(2021, 7, 14, 14, 38, 58, 269262, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Order Processing', 'Order Processing'), ('Order Completed', 'Order Completed'), ('Order Received', 'Order Received ')], max_length=50),
        ),
    ]
