# Generated by Django 3.1.5 on 2021-07-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0004_auto_20210714_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received '), ('On The Way', 'On The Way'), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing')], max_length=50),
        ),
    ]
