# Generated by Django 3.1.5 on 2021-07-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0007_auto_20210714_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received '), ('Order Completed', 'Order Completed'), ('On The Way', 'On The Way'), ('Order Processing', 'Order Processing')], max_length=50),
        ),
    ]
