# Generated by Django 3.1.5 on 2021-07-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0009_auto_20210721_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received '), ('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('On The Way', 'On The Way')], max_length=50),
        ),
    ]
