# Generated by Django 3.1.5 on 2021-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0010_auto_20210722_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Completed', 'Order Completed'), ('Order Processing', 'Order Processing'), ('Order Received', 'Order Received '), ('On The Way', 'On The Way')], max_length=50),
        ),
    ]
