# Generated by Django 3.1.5 on 2021-07-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitureshop', '0012_auto_20210725_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='messae',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Order Received', 'Order Received '), ('Order Completed', 'Order Completed'), ('On The Way', 'On The Way'), ('Order Processing', 'Order Processing')], max_length=50),
        ),
    ]
